# Generated by Django 5.0.6 on 2024-06-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='rua',
            new_name='logradouro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='endereco',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='mapa.empresa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_type', models.CharField(max_length=50)),
                ('odc', models.CharField(max_length=50)),
                ('consultor', models.CharField(max_length=255)),
                ('data_efetivacao', models.DateField()),
                ('validade', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='mapa.empresa')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificacao',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
